/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.HDCTDao;
import DAO.HoaDonDao;
import DAO.KhachHangDao;
import DAO.MenuDao;
import DAO.NhanVienDao;
import JDBC.DateHelper;
import JDBC.DialogHelper;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HDCT;
import model.HoaDon;
import model.KhachHang;
import model.Menu;
import model.NhanVien;

/**
 *
 * @author ADMIN
 */
public class HoaDonJFrame extends javax.swing.JFrame {

    int index = 0;
    MenuDao dao = new MenuDao();
    NhanVienDao nvdao = new NhanVienDao();
    KhachHangDao khdao = new KhachHangDao();
    HoaDonDao hdao = new HoaDonDao();
    HDCTDao ctdao = new HDCTDao();
    public static String MaSP;
    static int SoLuong;

    /**
     * Creates new form HoaDonJFrame
     */
    public HoaDonJFrame() {
        initComponents();
        this.setTitle("Hóa Đơn");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public boolean check() {
        if (txtMaHD.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống mã", "Error", 1);
            return false;
        } else if (!(txtMaHD.getText()).matches("HD[0-9][0-9]{1,9}")) {
            JOptionPane.showMessageDialog(rootPane, "Sai định dạng mã: HD001", "Error", 1);
            txtMaHD.requestFocus();
            return false;
        }
        return true;
    }

    void selectComboBox() {
        NhanVien nv = (NhanVien) cboTenNV.getSelectedItem();
    }

    void fillComboBox() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenNV.getModel();
        model.removeAllElements();
        try {
            List<NhanVien> listnv = nvdao.select();
            for (NhanVien nv : listnv) {
                model.addElement(nv);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void selectComboBoxKH() {
        KhachHang kh = new KhachHang();
        kh = (KhachHang) cboTenKH.getSelectedItem();
    }

    void fillComboBoxKH() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenKH.getModel();
        model.removeAllElements();
        try {
            List<KhachHang> listkh = khdao.select1();
            for (KhachHang kh : listkh) {
                model.addElement(kh);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    private void ThemCTHDTuTable(String MaHD) {
        for (int i = 0; i < tblDS.getRowCount(); i++) {

            String masp = tblDS.getValueAt(i, 1).toString();
            int soluong = Integer.parseInt(tblDS.getValueAt(i, 3).toString());
            float thanhtien = DateHelper.ChuyenTien(tblDS.getValueAt(i, 5).toString());

        }
    }

    void insert() {

        HDCT model = new HDCT();
        for (int i = 0; i < tblDS.getRowCount(); i++) {
            model.setMahd(txtMaHD.getText());
            model.setMasp(tblDS.getValueAt(i, 1).toString());
            model.setTensp(tblDS.getValueAt(i, 2).toString());
            model.setSoluong(Integer.parseInt(tblDS.getValueAt(i, 3).toString()));
            model.setThanhtien(DateHelper.ChuyenTien(tblDS.getValueAt(i, 5).toString()));
            try {
                ctdao.insert(model);

                System.out.println("thêm CTHD thành công!");
            } catch (Exception e) {
                System.out.println("Lỗi thêm CTHD!");
            }
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGridMenu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtThanhTien = new javax.swing.JTextField();
        txtNgayXuat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDS = new javax.swing.JTable();
        txtMaHD = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        cboTenKH = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        cboTenNV = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblGridMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MaSP", "TenSP", "Gia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGridMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGridMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGridMenu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Mã hóa đơn");

        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel6.setText("Tên nhân viên");

        jLabel7.setText("Tên khách hàng");

        jLabel9.setText("Tổng Tiền");

        jLabel10.setText("Ngày xuất hóa đơn");

        tblDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá", "ThanhTien"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDS);

        btnClear.setText("Tạo Mới");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnShow.setText("Xem HD");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(null);

        cboTenKH.setMaximumRowCount(10);
        cboTenKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenKHActionPerformed(evt);
            }
        });
        jScrollPane3.setViewportView(cboTenKH);

        jScrollPane4.setBorder(null);

        cboTenNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenNVActionPerformed(evt);
            }
        });
        jScrollPane4.setViewportView(cboTenNV);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhToan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnShow))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(txtNgayXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addContainerGap(380, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnThanhToan)
                    .addComponent(btnClear)
                    .addComponent(btnShow))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel8))
                        .addComponent(txtMaHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtNgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(331, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblGridMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGridMenuMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            MaSP = tblGridMenu.getValueAt(tblGridMenu.getSelectedRow(), 0).toString();
            addSP add = new addSP(this, true);
            add.setVisible(true);

            String tenSP = tblGridMenu.getValueAt(tblGridMenu.getSelectedRow(), 1).toString();
            float thanhTien, dongia;
            dongia = Float.parseFloat(tblGridMenu.getValueAt(tblGridMenu.getSelectedRow(), 2).toString());
            thanhTien = dongia * SoLuong;
            ThemSanPhamTbCTHD(MaSP, tenSP, SoLuong, dongia, thanhTien);
            txtThanhTien.setText(DateHelper.DinhDangTien(TinhTien()));
        }
    }//GEN-LAST:event_tblGridMenuMouseClicked
    private void ThemSanPhamTbCTHD(String maSP, String tenSP, int soLuong,
            float donGia, float thanhTien) {

        DefaultTableModel tbModel = (DefaultTableModel) tblDS.getModel();

        Object obj[] = new Object[6];

        obj[0] = tbModel.getRowCount() + 1;
        obj[1] = maSP;
        obj[2] = tenSP;
        obj[3] = soLuong;
        obj[4] = DateHelper.DinhDangTien(donGia);
        obj[5] = DateHelper.DinhDangTien(thanhTien);

        tbModel.addRow(obj);
    }

    private float TinhTien() {
        float tongTien = 0;
        for (int i = 0; i < tblDS.getRowCount(); i++) {
            tongTien += DateHelper.ChuyenTien(tblDS.getValueAt(i, 5).toString());
        }
        return tongTien;
    }

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        if (check()) {
            if (tblDS.getRowCount() <= 0) {
                JOptionPane.showMessageDialog(this, "Chưa chọn sản phẩm");
                return;
            }
            NhanVien nv = (NhanVien) cboTenNV.getSelectedItem();
            KhachHang kh = (KhachHang) cboTenKH.getSelectedItem();
            HoaDon model = new HoaDon();
            model.setMaHD(txtMaHD.getText());
            model.setMaNV(nv.getMaNV());
            model.setMaKH(kh.getMaKH());
            model.setThanhTien(DateHelper.ChuyenTien(txtThanhTien.getText()));
            model.setNgayXuatHD(DateHelper.toDate(txtNgayXuat.getText()));
            //Thêm hóa đơn vào database
            hdao.insert(model);
            //Thêm tất cả chi tiết hóa đơn theo MaHD vừa thêm
//            ThemCTHDTuTable(model.getMaHD());
            insert();
            //tạo lại hóa đơn mới
            TaoMoiHD();
            DialogHelper.alert(this, "Đã lưu Hóa đơn!");
        }


    }//GEN-LAST:event_btnThanhToanActionPerformed
    private void TaoMoiHD() {
        txtNgayXuat.setText(DateHelper.toString(new Date()));
        txtMaHD.setText("");
        txtThanhTien.setText("");
        DefaultTableModel tbModel = (DefaultTableModel) tblDS.getModel();
        tbModel.setRowCount(0);

    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        load();
        txtNgayXuat.setText(DateHelper.toString(new Date()));

        fillComboBox();
        fillComboBoxKH();
    }//GEN-LAST:event_formWindowOpened

    private void cboTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenNVActionPerformed
        // TODO add your handling code here:
        selectComboBox();
    }//GEN-LAST:event_cboTenNVActionPerformed

    private void cboTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenKHActionPerformed
        // TODO add your handling code here:
        selectComboBoxKH();
    }//GEN-LAST:event_cboTenKHActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtMaHD.setText("");
        txtThanhTien.setText("");
        DefaultTableModel tbModel = (DefaultTableModel)tblDS.getModel();
        tbModel.setRowCount(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        new ShowHD(this, true).setVisible(true);
    }//GEN-LAST:event_btnShowActionPerformed
    void load() {
        DefaultTableModel model = (DefaultTableModel) tblGridMenu.getModel();
        model.setRowCount(0);

        try {
            List<Menu> list = dao.select();
            for (Menu mn : list) {
                Object[] row = {
                    mn.getMaSP(),
                    mn.getTenSP(),
                    mn.getGia(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JComboBox<String> cboTenKH;
    private javax.swing.JComboBox<String> cboTenNV;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblDS;
    private javax.swing.JTable tblGridMenu;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtNgayXuat;
    private javax.swing.JTextField txtThanhTien;
    // End of variables declaration//GEN-END:variables
}
